modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="emoji"
version="1.0.0"
displayName="Emoji"
description="Colon chat completion and custom RGBA color emojis."

[[dependencies.emoji]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.emoji]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
