modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/Toxicbullet-code/emoji-mod/issues"

[[mods]]
modId="emoji"
version="1.0.0"
displayName="Emoji Mod"
credits="Created by toxic_bullet"
authors="toxic_bullet"
description='''
A lightweight client-side Minecraft Forge mod that brings Discord-style inline chat autocomplete and custom RGBA rendering to chat.
'''

[[dependencies.emoji]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.emoji]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="CLIENT"
